<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Feature-Extraction" data-toc-modified-id="Feature-Extraction-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Feature Extraction</a></span></li><li><span><a href="#Results" data-toc-modified-id="Results-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Results</a></span></li></ul></div>

# Feature Extraction


As a first step, I will perform feature extraction. The results of this step will be saved as a dataframe and will be used in the next step.

In [1]:
import pandas as pd
import re
import numpy as np
import scipy as sp
from textblob import TextBlob
from textblob import Word
import language_check
import enchant
import sys
sys.path.append("C://Users//mohammad//Desktop//khalili")
import Preprocess as pss

In [2]:
df = pd.read_csv("C://Users//mohammad//Desktop//khalili//challenge.csv" , encoding = "latin1")
df.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,domain1_score
0,1,1,"Dear local newspaper, I think effects computer...",4.0,4.0,8.0
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5.0,4.0,9.0
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4.0,3.0,7.0
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5.0,5.0,10.0
4,5,1,"Dear @LOCATION1, I know having computers has a...",4.0,4.0,8.0

I have written a class to extarct the features. The features include number of words, number of sentences, average length of sentences, number of long words, the polarity of the essay, number of nouns, number of verbs, number of adverbs, number of adjectives, number of grammer mistakes and number of spelling mistakes. The code of this class can be find in a file called "Preprocess.py"

In [3]:
prepro = pss.PreprocessData()

In [4]:
prepro.processData(df)

# Results

In [5]:
df.head()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,domain1_score,*_# of words_*,*_# of sentences_*,*_Average lenght of sentences_*,*_# of large words_*,*_Sentiment_Polarity_*,*_# of Nouns_*,*_# of Verbs_*,*_# of Adverbs_*,*_# of Adjectives_*,*_# of grammer mistakes_*,*_# of spelling mistakes*
0,1,1,"Dear local newspaper, I think effects computer...",4.0,4.0,8.0,343.0,16.0,21.125000,59.0,0.310471,84.0,68.0,26.0,20.0,11.0,21.0
1,2,1,"Dear @CAPS1 @CAPS2, I believe that using compu...",5.0,4.0,9.0,422.0,20.0,20.950000,81.0,0.274000,114.0,85.0,20.0,21.0,19.0,20.0
2,3,1,"Dear, @CAPS1 @CAPS2 @CAPS3 More and more peopl...",4.0,3.0,7.0,283.0,14.0,19.928571,52.0,0.340393,86.0,53.0,18.0,19.0,9.0,5.0
3,4,1,"Dear Local Newspaper, @CAPS1 I have found that...",5.0,5.0,10.0,527.0,27.0,19.407407,131.0,0.266828,200.0,98.0,30.0,52.0,35.0,22.0
4,5,1,"Dear @LOCATION1, I know having computers has a...",4.0,4.0,8.0,470.0,30.0,15.500000,87.0,0.199684,116.0,87.0,39.0,30.0,17.0,25.0

In [6]:
df.tail()

,essay_id,essay_set,essay,rater1_domain1,rater2_domain1,domain1_score,*_# of words_*,*_# of sentences_*,*_Average lenght of sentences_*,*_# of large words_*,*_Sentiment_Polarity_*,*_# of Nouns_*,*_# of Verbs_*,*_# of Adverbs_*,*_# of Adjectives_*,*_# of grammer mistakes_*,*_# of spelling mistakes*
12973,21626,8,In most stories mothers and daughters are eit...,17.0,18.0,35.0,863.0,27.0,31.370370,98.0,0.146336,211.0,178.0,73.0,56.0,15.0,19.0
12974,21628,8,I never understood the meaning laughter is th...,15.0,17.0,32.0,556.0,35.0,15.628571,53.0,0.147192,158.0,99.0,54.0,47.0,41.0,10.0
12975,21629,8,"When you laugh, is @CAPS5 out of habit, or is ...",20.0,26.0,40.0,827.0,41.0,19.926829,161.0,0.131967,230.0,172.0,63.0,57.0,23.0,15.0
12976,21630,8,Trippin' on fen...,20.0,20.0,40.0,576.0,39.0,15.205128,91.0,-0.001249,122.0,111.0,55.0,43.0,13.0,16.0
12977,21633,8,Many people believe that laughter can improve...,20.0,20.0,40.0,475.0,29.0,16.137931,72.0,0.247257,105.0,100.0,40.0,40.0,3.0,8.0

In [7]:
df.to_csv("C://Users//zzare//Desktop//khalili//data.csv")

Next step is in "Main_1.ipynb"